#ifndef _NS_VSERV_HELPERS_H_
#define _NS_VSERV_HELPERS_H_

#define GS_VSERV_USER_ID_INVALID 0xFFFF
#define GS_VSERV_USER_ID_SERVFILL 0xFFFF

enum GsVServCmd {
	GS_VSERV_CMD_BROADCAST = 'b',
	GS_VSERV_M_CMD_GROUPSET = 's',
	GS_VSERV_CMD_GROUP_MODE_MSG = 'm',
	GS_VSERV_CMD_IDENT = 'i',
	GS_VSERV_CMD_IDENT_ACK = 'I',
	GS_VSERV_CMD_NAMEGET = 'n',
	GS_VSERV_CMD_NAMES = 'N',
	GS_VSERV_CMD_IDGET = 'd',
	GS_VSERV_CMD_IDS   = 'D',
	GS_VSERV_CMD_PING  = 'p',
};

#define GS_MACRO_VSERV_CMD_ONE(NAME) { NAME, # NAME }
#define GS_MACRO_VSERV_CMD_LIST() { \
		GS_MACRO_VSERV_CMD_ONE(GS_VSERV_CMD_BROADCAST), \
		GS_MACRO_VSERV_CMD_ONE(GS_VSERV_M_CMD_GROUPSET), \
		GS_MACRO_VSERV_CMD_ONE(GS_VSERV_CMD_GROUP_MODE_MSG), \
		GS_MACRO_VSERV_CMD_ONE(GS_VSERV_CMD_IDENT), \
		GS_MACRO_VSERV_CMD_ONE(GS_VSERV_CMD_IDENT_ACK), \
		GS_MACRO_VSERV_CMD_ONE(GS_VSERV_CMD_NAMEGET), \
		GS_MACRO_VSERV_CMD_ONE(GS_VSERV_CMD_NAMES), \
		GS_MACRO_VSERV_CMD_ONE(GS_VSERV_CMD_IDGET), \
		GS_MACRO_VSERV_CMD_ONE(GS_VSERV_CMD_IDS), \
		GS_MACRO_VSERV_CMD_ONE(GS_VSERV_CMD_PING), \
	}
#define GS_MACRO_VSERV_CMD_LIST_VAR(VARNAME) \
	struct { int mNum; const char *mStr; } VARNAME[] = GS_MACRO_VSERV_CMD_LIST(); \
	size_t VARNAME ## Num = sizeof VARNAME / sizeof *VARNAME;

enum GsVServGroupMode
{
	GS_VSERV_GROUP_MODE_NONE = 0,
	GS_VSERV_GROUP_MODE_S = 's',
};

#endif /* _NS_VSERV_HELPERS_H_ */
