FIND_PATH(ENET_INCLUDE_DIR NAMES enet.h
  PATH_SUFFIXES enet)

FIND_LIBRARY(ENET_LIBRARY NAMES enet)

SET(ENET_LIBRARIES ${ENET_LIBRARY})

# unfortunately extra libraries may be required
IF (ENET_LIBRARIES AND WIN32)
  LIST(APPEND ENET_LIBRARIES ws2_32 winmm)
ENDIF ()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ENet DEFAULT_MSG ENET_INCLUDE_DIR ENET_LIBRARY ENET_LIBRARIES)

MARK_AS_ADVANCED(ENET_INCLUDE_DIR ENET_LIBRARY ENET_LIBRARIES)
